import { createClient } from '@supabase/supabase-js';

const sb = createClient(
  'https://bzlllfmpojcybuyuemdx.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6bGxsZm1wb2pjeWJ1eXVlbWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwMzQ1NjQsImV4cCI6MjA4NjYxMDU2NH0.A1nGk9fsNgukxo4WggzFF-lgOFHDaCJS0phbeldx6xY'
);

const paysageTitres = {
  'mer-2':   'Pointu sur turquoise — Marseille',
  'mer-4':   'Entre deux eaux — Calanques',
  'mer-6':   "L'oeil de la grotte — Apnée",
  'mer-10':  'Kayaks sous les falaises — Calanques',
  'mer-12':  'Cathédrale calcaire — Calanques',
  'mer-13':  'Crépuscule de calanque — Marseille',
  'mer-14':  'Silhouettes et reflets — Notre-Dame',
  'mer-20':  'Vallon des Auffes doré — Marseille',
  'mer-22':  'Robe rouge sur roche rouge — Marseille',
  'mer-23':  "L'aiguille et le cristal — Calanques",
  'mer-30':  'Poisson des murs — Street art Marseille',
  'mer-32':  "Fisheye sur l'infini — Calanques",
  'mer-33':  'Nageur des eaux rouges — Marseille',
  'mer-35':  'Plongée aérienne — Calanques de Marseille',
  'mer-39':  'Calanque sauvage — Marseille',
  'mer-44':  'Les bras ouverts aux Calanques',
  'mer-45':  'Miroir de plage — Marseille',
  'mer-46':  "L'arbre gardien — Calanques",
  'mer-47':  'Vagues vues du ciel — Méditerranée',
  'mer-50':  'Calanque secrète — Marseille',
  'mer-51':  'Or et turquoise — Calanques au crépuscule',
  'mer-52':  'La Vierge surplombe la mer — Marseille',
  'mer-54':  'En-Vau vu des anges — Calanques',
  'mer-55':  'La mer commence ici — Pollution urbaine',
  'mer-56':  'Cadenas et voiliers — Vieux-Port',
  'mer-57':  'Poulies et Notre-Dame de la Garde',
  'mer-58':  'Pirate du Vieux-Port — Marseille',
  'mer-59':  'Sculpture sous les flots — Musée subaquatique',
  'mer-60':  'Vallon des Auffes nocturne — Marseille',
  'mer-61':  'Canette au fond des mers — Pollution marine',
  'mer-62':  'Voile rouge sur Marseille',
  'mer-63':  'Bouée et Notre-Dame de la Garde',
  'mer-64':  'Le Kraken et le pointu — Calanques',
  'mer-66':  'Colère du mistral — Méditerranée',
  'mer-67':  'Véliplanchiste des Calanques — Marseille',
  'mer-68':  'Trois voiles au coucher — Méditerranée',
  'mer-70':  'Panorama des Calanques — Notre-Dame de la Garde',
  'mer-72':  'Méduse rose en suspension — Méditerranée',
  'mer-73':  'Goéland sentinelle — Port de Marseille',
  'mer-74':  'Barques sous les falaises — Calanques',
  'mer-75':  'Maisons de pêcheurs — Calanques de Marseille',
  'mer-76':  'Récolte du Projet Sentinelle — Dépollution',
  'mer-78':  'Port de calanque en HDR — Marseille',
  'mer-79':  'Le pointu et son reflet — Calanques',
  'mer-80':  'Barque et falaises — Calanques de Marseille',
  'mer-81':  'Nageur solitaire vu du ciel — Calanques',
  'mer-82':  'Étoile de mer rouge — Méditerranée',
  'mer-83':  'Sormiou azuréen — Calanques de Marseille',
  'mer-86':  'Archipel du Frioul — Marseille',
  'mer-87':  'Marseille vue depuis la mer',
  'mer-89':  'Apnée dans les Calanques — Dark Massilia',
  'mer-90':  'Faune et flore marines — Calanques',
  'mer-91':  'Posidonie des Calanques — Méditerranée',
  'mer-92':  "Lumière filtrée sous l'eau — Calanques",
  'mer-94':  'Biodiversité méditerranéenne — Calanques',
  'mer-95':  'Fonds du Frioul — Apnée Marseille',
  'mer-97':  'Frioul turquoise — Marseille',
  'mer-98':  'Îlots des Gabian — Marseille',
  'mer-99':  'Sormiou et ses eaux — Calanques',
  'mer-100': 'Côte landaise — Capbreton Atlantique',
  'mer-portfolio-paysages-env': 'Portfolio photographe sous-marin Marseille',
  'terre-1':  'Lumière dans la lavande — Provence',
  'terre-3':  'Rangées de Valensole au coucher',
  'terre-5':  'Chapeau et lavande violette — Provence',
  'terre-7':  'Vieil homme de Chefchaouen — Maroc',
  'terre-8':  'Robe bleue en Provence — Valensole',
  'terre-9':  'Portrait dans les lavandes — Provence',
  'terre-15': 'Carrousel au Vieux-Port — Marseille',
  'terre-16': 'Chaton roux de Chefchaouen — Maroc',
  'terre-17': 'La ville bleue du Maroc — Chefchaouen',
  'terre-18': 'Chaton blanc et marches bleues — Maroc',
  'terre-19': 'Deux chats en bleu — Chefchaouen',
  'terre-21': 'Robe rouge sur roche noire — Côte sauvage',
  'terre-24': 'Dune du Pilat au crépuscule — Arcachon',
  'terre-25': 'Coccinelle sur lavande — Macro Provence',
  'terre-26': 'Tournesols et lavande vus du ciel',
  'terre-27': 'Short jaune dans la lavande — Valensole',
  'terre-28': 'Couple dans la lavande — Provence',
  'terre-29': "Ciel d'orange sur Valensole",
  'terre-31': "L'arbre solitaire de Provence",
  'terre-34': 'Chapeau blanc et coquelicots — Provence',
  'terre-36': 'Le Corbusier à Marseille — Architecture',
  'terre-37': 'Cigognes du Maroc — Faune sauvage',
  'terre-38': 'Médina sous le soleil — Maroc',
  'terre-40': 'Tulipes roses de Provence',
  'terre-41': 'Chapeau de paille et tulipes multicolores',
  'terre-42': 'Robe rouge dans le reflet — Provence',
  'terre-43': 'Crépuscule lavande — Valensole',
  'terre-48': 'Géométrie de lavande — Vue du ciel',
  'terre-49': 'Lavande et montagnes — Provence',
  'terre-53': 'Lavande et tournesols — Contraste Provence',
  'terre-54': 'Paysage méditerranéen doré — Provence',
  'terre-85': 'Stade et littoral marseillais — Panorama',
};

const sousMarine = [
  'Apnéiste en mission — Projet Sentinelle',
  'Barquette du Frioul 1 — Dépollution Marseille',
  'Barquette du Frioul 2 — Projet Sentinelle',
  'Barquette du Frioul 3 — Nettoyage marin',
  'Barquette du Frioul 4 — Mission Sentinelle',
  'Barquette du Frioul 5 — Dépollution Calanques',
  'Barquette du Frioul 6 — Team Oxygen',
  'Barquette du Frioul 8 — Calanques de Marseille',
  'Bâche des profondeurs — Plastique sous-marin',
  'Barrière immergée — Pollution marine Marseille',
  'Bateau Sentinelle — Mission dépollution',
  'Bouteille dans les algues — Pollution mer',
  'Canette au fond des mers — Plastique Méditerranée',
  'Déchets ramassés — Projet Sentinelle Marseille',
  'Escargot de mer — Faune Calanques',
  'Fonds marins des Calanques — Biodiversité',
  'Frioul nettoyé — Mission 1 Sentinelle',
  'Frioul nettoyé — Mission 4 Sentinelle',
  'Frioul nettoyé — Mission 8 Sentinelle',
  "Esprit d'équipe aux Goudes — Dark Massilia",
  'Grotte de Riou — Exploration sous-marine',
  'Grotte marine — Apnée Calanques de Marseille',
  "L'Huveaune dépollué — Projet Sentinelle",
  'Kayak à Boudmer — Dépollution maritime',
  'Mer de plastique — Pollution Méditerranée',
  'Morgan Bourchis en mission — Champion apnée',
  'Moyades — Romuald et les fonds',
  'Moyades sous-marine — Calanques de Marseille',
  'Le Musée subaquatique des Calanques',
  'Musée subaquatique 1 — Sculptures marines',
  'Musée subaquatique 2 — Art sous les flots',
  'Vie marine du musée — Biodiversité Méditerranée',
  'Nage en calanque — Apnée Marseille',
  'Nage en apnée — Calanques de Marseille',
  'Plaque immatriculée au fond — Pollution marine',
  "Pollution de l'Huveaune — Marseille",
  'Poséidon des mers — Mission Sentinelle',
  'Poulpe sentinelle — Faune marine Calanques',
  'Shooting en grotte — Apnée Calanques',
  'Shooting sous-marin — Dark Massilia Marseille',
  'Soupe de plastique — Pollution Méditerranée',
  'Spirographe des fonds — Biodiversité marine',
  'Team Oxygen en freediving — Marseille',
  'Team Oxygen réunie — Projet Sentinelle',
  'Vélo-Métropole immergé — Pollution marine',
  'Vélo au fond de la mer — Calanques',
  "Angel sous l'eau — Apnée Calanques",
  'Barquette du Frioul 7 — Dépollution Marseille',
  'Plongée en diving — Calanques de Marseille',
  'Frioul nettoyé 7 — Mission Sentinelle',
  'Frioul nettoyé 9 — Dépollution Calanques',
  'Mer des Goudes — Calanques de Marseille',
  'Musée subaquatique — Sculptures marines',
  'Musée subaquatique 3 — Vie sous-marine',
  'Octopus calanques — Faune Méditerranée',
  'Paysage sous-marin — Calanques de Marseille',
  'Dépollution posidonie — Projet Sentinelle',
  'Mission dépollution — Team Oxygen Marseille',
  'Fonds des Calanques — Apnée Marseille',
  'Apnéiste certifié — Compétition freediving',
  'Morgan Bourchis triple champion — Apnée',
  'Plongeurs méditerranéens — Dark Massilia',
  'Apnéiste explorateur — Fonds marins Marseille',
  'Dépollution maritime — Calanques Marseille',
  'Pneu aux Goudes — Pollution marine Marseille',
  'Kayak Sentinelle — Opération dépollution',
  'Photo sous-marine — Team Oxygen Dark Massilia',
  'Port des Goudes nettoyé — Projet Sentinelle',
  'Caractérisation des déchets — Sentinelle',
  'TF1 Projet Sentinelle — Marseille reportage',
];

async function run() {
  console.log('Mise à jour des titres paysage…');
  let ok = 0;
  for (const [uid, title] of Object.entries(paysageTitres)) {
    const { error } = await sb.from('photos_paysage').update({ title }).eq('uid', uid);
    if (!error) ok++;
  }
  console.log(`✅ photos_paysage : ${ok}/${Object.keys(paysageTitres).length} titres`);

  console.log('Mise à jour des titres sous-marine…');
  let ok2 = 0;
  for (let i = 0; i < sousMarine.length; i++) {
    const { error } = await sb.from('photos_sous_marine').update({ title: sousMarine[i] }).eq('uid', `sentinelle-${i}`);
    if (!error) ok2++;
  }
  console.log(`✅ photos_sous_marine : ${ok2}/${sousMarine.length} titres`);
  console.log('\n🎉 Titres mis à jour !');
}

run();
